### ISSUE TITLE
날짜가 틀린거 같아욥?

### ISSUE THREAD

**Issue by bamjun** [ioimmini/ioimmini.github.io#5]
2023-12 일꺼 같아욥..

https://github.com/ioimmini/ioimmini.github.io/blob/f08ab7ee5ddf3f828a51c60b4c8b0e73c3bc7085/gatsby-site-meta-data.ts#L69

**Comment by ioimmini** [comment]
와 감사해여 어 ㅋㅋㅋ ㅋㅋㅋㅋㅋㅋㅋㅋ 아나  ㅋㅋㅋㅋ 모임 깜짝놀랬잖아여
